from __future__ import annotations

import hashlib
import shutil
from dataclasses import asdict, dataclass
from pathlib import Path, PurePosixPath
from typing import Any, Iterable

import pandas as pd
import yaml

from .validator import ValidationError


@dataclass(frozen=True)
class TrainingArtifact:
    """Useful files generated by an Ultralytics training run."""

    root: Path
    best_weights: Path
    last_weights: Path | None
    args_yaml: Path | None
    results_csv: Path | None
    dataset_yaml: Path | None
    file_count: int
    training_args: dict[str, Any]
    final_training_metrics: dict[str, float | str | None]

    def as_dict(self) -> dict[str, Any]:
        data = asdict(self)
        for key in ("root", "best_weights", "last_weights", "args_yaml", "results_csv", "dataset_yaml"):
            data[key] = str(data[key]) if data[key] is not None else None
        return data


def _first_file(root: Path, filename: str) -> Path | None:
    files = sorted(root.rglob(filename), key=lambda item: (len(item.parts), str(item)))
    return files[0] if files else None


def _read_args(path: Path | None) -> dict[str, Any]:
    if path is None:
        return {}
    try:
        content = yaml.safe_load(path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError):
        return {}
    return content if isinstance(content, dict) else {}


def _training_summary(path: Path | None) -> dict[str, float | str | None]:
    if path is None:
        return {}
    try:
        row = pd.read_csv(path).tail(1)
    except (OSError, ValueError, pd.errors.ParserError):
        return {}
    if row.empty:
        return {}
    result: dict[str, float | str | None] = {}
    for column, value in row.iloc[0].items():
        clean_name = str(column).strip()
        if any(token in clean_name.lower() for token in ("precision", "recall", "map50", "map50-95", "fitness", "epoch")):
            result[clean_name] = float(value) if isinstance(value, (int, float)) and pd.notna(value) else str(value)
    return result


def _dataset_from_args(args: dict[str, Any], args_path: Path | None) -> Path | None:
    value = args.get("data")
    if not isinstance(value, str) or not value.lower().endswith((".yaml", ".yml")):
        return None
    candidate = Path(value)
    if candidate.is_absolute() and candidate.is_file():
        return candidate
    if args_path is not None:
        relative = args_path.parent / candidate
        if relative.is_file():
            return relative
    return None


def inspect_training_folder(folder: Path) -> TrainingArtifact:
    """Find standard Ultralytics artifacts in an existing training folder."""
    root = folder.expanduser().resolve()
    if not root.is_dir():
        raise ValidationError("A pasta do treinamento não existe ou não pode ser acessada.")
    best_weights = _first_file(root, "best.pt")
    if best_weights is None:
        raise ValidationError("A pasta enviada não contém weights/best.pt. Selecione a pasta final de um treinamento YOLO.")
    args_yaml = _first_file(root, "args.yaml") or _first_file(root, "opt.yaml")
    args = _read_args(args_yaml)
    dataset_yaml = _dataset_from_args(args, args_yaml)
    if dataset_yaml is None:
        dataset_yaml = _first_file(root, "data.yaml") or _first_file(root, "data.yml")
    return TrainingArtifact(
        root=root,
        best_weights=best_weights,
        last_weights=_first_file(root, "last.pt"),
        args_yaml=args_yaml,
        results_csv=_first_file(root, "results.csv"),
        dataset_yaml=dataset_yaml,
        file_count=sum(1 for item in root.rglob("*") if item.is_file()),
        training_args=args,
        final_training_metrics=_training_summary(_first_file(root, "results.csv")),
    )


def materialize_uploaded_folder(files: Iterable[Any], destination: Path) -> Path:
    """Store a directory-upload safely so YOLO can load its weights from disk."""
    uploaded = list(files)
    if not uploaded:
        raise ValidationError("Envie a pasta completa do treinamento.")
    destination.mkdir(parents=True, exist_ok=True)
    for item in uploaded:
        parts = PurePosixPath(item.name.replace("\\", "/")).parts
        if not parts or any(part in {"", ".", ".."} for part in parts):
            raise ValidationError("A pasta enviada contém um caminho de arquivo inválido.")
        target = destination.joinpath(*parts)
        target.parent.mkdir(parents=True, exist_ok=True)
        with target.open("wb") as output:
            shutil.copyfileobj(item, output)
    return destination


def shared_dataset_path(old: TrainingArtifact, new: TrainingArtifact) -> Path | None:
    """Return a data YAML only when both runs carry the exact same file."""
    if old.dataset_yaml is None or new.dataset_yaml is None:
        return None
    try:
        old_hash = hashlib.sha256(old.dataset_yaml.read_bytes()).digest()
        new_hash = hashlib.sha256(new.dataset_yaml.read_bytes()).digest()
    except OSError:
        return None
    return old.dataset_yaml if old_hash == new_hash else None
